### ISSUE TITLE
Install error after clone

### ISSUE THREAD

**Issue by WKenya** [romancm/gamebrary#111] opened 2019-05-18 22:34 UTC
# Bug report
Can't run successfully run `yarn` after cloning the repo.

## Description of the problem
When running `yarn` off a new clone I get the following error:
```
[1/5] Validating package.json...
[2/5] Resolving packages...
[3/5] Fetching packages...
error An unexpected error occurred: "https://infusionsoft.jfrog.io/infusionsoft/api/npm/npm/masonry-layout/-/masonry-layout-4.2.2.tgz: Request failed \"401 Unauthorized\"".
```
### Your Environment
| Software         | Name/Version|
| ---------------- | ---------- |
| Browser | N/A |
| Operating System | Windows 10 |

**Comment by Swinkid** [comment] 2019-05-18 22:39
Can you retry running yarn?

For reference to others - Not having this issue when cloning new repository and running yarn. I am having issue directly navigating to the tgz file through chrome.

**Comment by WKenya** [comment] 2019-05-18 23:25
I tried it again and it did not work. I upgraded my yarn which did not help. I also navigated to the url of the file and got a login prompt.

I also tried a cache clean for yarn which did not help either.

**Comment by romancm** [comment] 2019-05-19 01:23
Oops, remove your yarn.lock file and try running yarn again. I'll push the fix in a bit

**Comment by romancm** [comment] 2019-05-19 01:27
Pushed fix, try pulling down again, should work now.

**Comment by romancm** [comment] 2019-05-19 04:28
@allcintributors please add @WKenya for bug

**Comment by romancm** [comment] 2019-05-19 04:31
@all-contributors please add @WKenya for bug

**Comment by romancm** [comment] 2019-05-20 16:41
Closing this for now as I cannot reproduce it anymore. Feel free to reopen it if issue persists.

**Closed by romancm** 2019-05-20 16:41 UTC
Labels: bug

**Comment by WKenya** [comment] 2019-05-20 23:08
This fixed my issue, thanks!
