### ISSUE TITLE
My boards have disappeared

### ISSUE THREAD

**Issue by lindyhop** [romancm/gamebrary#217] opened 2020-09-26 01:39 UTC
**Describe the bug**
After the latest (?) UI change, I cannot access my boards anymore.

I am logged in, I can create a new board (or at least start the wizard, but I haven't followed through for fear of blowing any existing data away), and when I click on the box that says "Games" and has round icons of the systems I've chosen, it flashes the outlines of some boards for a moment (grey shaded box art and titles, but not enough titles in the second column to be my old boards), and pops up "There was an error loading boards"

**To Reproduce**
1. Log in
2. Click on "Games" card

**Expected behavior**
See four boards: Steam, physical Switch, and digital Switch with games in each.

**Screenshots**
-

**Desktop (please complete the following information):**
macOS Mojave (10.14.2)
Chrome (85.0.4183.102)

**Comment by gamebrary** [comment] 2020-09-28 15:52
This is a duplicate of https://github.com/romancm/gamebrary/issues/205, I will have the fix out soon, in the mean time, the workaround is to sign out and login again to fix this issue.

**Comment by gamebrary** [comment] 2020-09-28 23:48
Fix for expired session handling has been deployed, closing this ticket, feel free to reopen if you continue to experience issues.

**Closed by gamebrary** 2020-09-28 23:48 UTC
Labels: duplicate

**Comment by gamebrary** [comment] 2022-08-22 19:58
@all-contributors please add @lindyhop for bug
